"""initial_schema

Revision ID: 0d2d4063362d
Revises: 
Create Date: 2026-06-08 16:21:15.567241

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '0d2d4063362d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
